# Generated by Django 5.0.14 on 2025-08-02 04:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_vgpuser_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vgpuser",
            name="profile_picture",
        ),
    ]
