"""
Django settings for vgpPortal project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

CAPTCHA_IMAGE_SIZE = (120, 40)   # (width, height)

# Length of captcha text
CAPTCHA_LENGTH = 4               # Number of characters

import random

def numeric_captcha_challenge():
    # Generate a random numeric string of CAPTCHA_LENGTH
    text = ''.join(random.choices(CAPTCHA_CHARS, k=CAPTCHA_LENGTH))
    return text, text  # Both the displayed and validation text

CAPTCHA_CHALLENGE_FUNCT = 'vgpPortal.settings.numeric_captcha_challenge'
# Character set
CAPTCHA_CHARS = '0123456789'  # Avoid confusing chars

# Timeout for captcha validity (in minutes)
CAPTCHA_TIMEOUT = 5

# Noise and complexity
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots')  # Both lines & dots
CAPTCHA_FILTER_FUNCTIONS = ('captcha.helpers.post_smooth',)  # Smooth effect

# Font settings
CAPTCHA_FONT_SIZE = 32
#CAPTCHA_FONT_PATH = '/path/to/font.ttf'  # Optional custom font

# Background and foreground colors
CAPTCHA_FOREGROUND_COLOR = "#ffffff"
CAPTCHA_BACKGROUND_COLOR = '#275C76'

# Case sensitivity
CAPTCHA_LETTER_CASE = 'upper'   # Options: 'upper', 'lower', or None (mixed)



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-j7!2y(bp2b6a2_pwt7e5qrn91h4jffj6f)+ajm(=$atnut5j+&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'accounts',
    'captcha',
    'main',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vgpPortal.urls"
AUTH_USER_MODEL = 'accounts.VGPUser'
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vgpPortal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'mssql',
        'NAME': 'VGPSYSTEM',
        'USER': 'sa',
        'PASSWORD': 'Sachin@99',
        'HOST': 'localhost',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
