# Generated by Django 5.0.14 on 2025-07-23 05:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "ID",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobno", models.CharField(max_length=15)),
                ("org", models.CharField(blank=True, max_length=100, null=True)),
                ("idt", models.CharField(max_length=50)),
                ("idno", models.CharField(max_length=20)),
                ("deptt", models.CharField(blank=True, max_length=100, null=True)),
                ("desig", models.CharField(blank=True, max_length=100, null=True)),
                ("rcode", models.CharField(blank=True, max_length=20, null=True)),
                ("gndr", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("vsttype", models.CharField(blank=True, max_length=50, null=True)),
                ("vstpurpose", models.TextField(blank=True, null=True)),
                ("vstdeptt", models.CharField(blank=True, max_length=100, null=True)),
                ("vstname", models.CharField(blank=True, max_length=100, null=True)),
                ("vstmobno", models.CharField(blank=True, max_length=15, null=True)),
                ("vstemail", models.EmailField(blank=True, max_length=150, null=True)),
                ("vstdates", models.CharField(blank=True, max_length=15, null=True)),
                ("vststartdt", models.DateField(blank=True, max_length=15, null=True)),
                ("vstenddt", models.DateField(blank=True, max_length=15, null=True)),
                ("vstdays", models.IntegerField(blank=True, null=True)),
                ("vehicleno", models.CharField(blank=True, max_length=50, null=True)),
                ("vehicletype", models.CharField(blank=True, max_length=50, null=True)),
                ("drivername", models.CharField(blank=True, max_length=100, null=True)),
                ("driveridno", models.CharField(blank=True, max_length=50, null=True)),
                ("vstcreatedon", models.DateTimeField(blank=True, null=True)),
                ("vstupdatedon", models.DateTimeField(blank=True, null=True)),
                ("vstmembers", models.TextField(blank=True, null=True)),
                ("vstmemberscount", models.IntegerField(blank=True, null=True)),
                (
                    "vstipaddress",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vstuseragent",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("vststatus", models.CharField(blank=True, max_length=50, null=True)),
                ("vstremarks", models.TextField(blank=True, null=True)),
                (
                    "vststatusupdby",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vststatusupdon", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
