# Generated by Django 5.0.14 on 2025-07-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_id_visit_id_visit_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="uid",
            field=models.CharField(max_length=50),
        ),
    ]
