# Generated by Django 5.0.14 on 2025-08-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_visit_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="vehicle",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
